server.port: 8081
spring:
  main.allow-bean-definition-overriding: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/feignclientdb
    username: root
    password: supersecure
  jpa.hibernate:
    ddl-auto: none
    use-new-id-generator-mappings: false
feign:
  hystrix:
    enabled: false