server.port: 8081
spring:
  main.allow-bean-definition-overriding: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/feignclientdb
    username: root
    password: supersecure
  jpa.hibernate.ddl-auto: none
feign:
  hystrix:
    enabled: true