server.port: 8082
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/feignclientdb
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: supersecure
  jpa.hibernate.ddl-auto: none